all:
	$(MAKE) -C common	  all
	$(MAKE) -C ENN	      all
	$(MAKE) -C process	  all
	$(MAKE) -C interface  all

clean:
	$(MAKE) -C common	  clean
	$(MAKE) -C ENN	      clean
	$(MAKE) -C process	  clean
	$(MAKE) -C interface  clean